#!/usr/bin/env bash
set -x
set -eo pipefail

# if a redis container is running, print instructions to kill it and exit
RUNNING_CONTAINER=$(docker ps --filter "name=redis" --format "{{.ID}}")

if [[ -n "$RUNNING_CONTAINER" ]]; then
  echo >&2 "Error: A Redis container is already running. Please stop it before running this script."
  echo >&2 "You can stop it using the following command:"
  echo >&2 "        docker kill ${RUNNING_CONTAINER}"
  exit 1
fi

# Launch Redis container
docker run -d --name "redis_$(date '+%s')" -p "6379:6379" redis:latest

>&2 echo "Redis container launched successfully. You can connect to it on localhost:6379."
